# Generated by Django 2.0.2 on 2018-02-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('game', models.IntegerField()),
                ('ab', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('hit', models.IntegerField()),
                ('single', models.IntegerField()),
                ('double', models.IntegerField()),
                ('triple', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('run', models.IntegerField()),
                ('rbi', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('ibb', models.IntegerField()),
                ('so', models.IntegerField()),
                ('hbp', models.IntegerField()),
                ('playerid', models.IntegerField()),
                ('year', models.IntegerField()),
                ('p1b', models.FloatField()),
                ('p2b', models.FloatField()),
                ('p3b', models.FloatField()),
                ('phr', models.FloatField()),
                ('ptw', models.FloatField()),
                ('pso', models.FloatField()),
                ('pbo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('game', models.IntegerField()),
                ('ab', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('hit', models.IntegerField()),
                ('single', models.IntegerField()),
                ('double', models.IntegerField()),
                ('triple', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('run', models.IntegerField()),
                ('rbi', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('ibb', models.IntegerField()),
                ('so', models.IntegerField()),
                ('hbp', models.IntegerField()),
                ('year', models.IntegerField()),
                ('p1b', models.FloatField()),
                ('p2b', models.FloatField()),
                ('p3b', models.FloatField()),
                ('phr', models.FloatField()),
                ('ptw', models.FloatField()),
                ('pso', models.FloatField()),
                ('pbo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('playerid', models.IntegerField()),
                ('year', models.IntegerField()),
                ('team', models.CharField(max_length=50)),
                ('ip', models.FloatField()),
                ('tbf', models.IntegerField()),
                ('hit', models.IntegerField()),
                ('single', models.IntegerField()),
                ('double', models.IntegerField()),
                ('triple', models.IntegerField()),
                ('run', models.IntegerField()),
                ('er', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('ibb', models.IntegerField()),
                ('hbp', models.IntegerField()),
                ('so', models.IntegerField()),
                ('p1b', models.FloatField()),
                ('p2b', models.FloatField()),
                ('p3b', models.FloatField()),
                ('phr', models.FloatField()),
                ('ptw', models.FloatField()),
                ('pso', models.FloatField()),
                ('pbo', models.FloatField()),
            ],
        ),
    ]
